docs: new python tutorial
applandinc/vscode-appland pull request #140
Opened 2021-02-24 22:08 UTC by ptrdvrk

2021-02-24 22:39 UTC, apotterri approved these changes
A couple of comments, looks good, though.

2021-02-24 22:39 UTC, apotterri commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +% git clone -b master git@github.com:chicagopython/chipy.org.git
This can use the `https` URL, no? https://github.com/chicagopython/chipy.org.git

2021-02-24 22:39 UTC, apotterri commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +This tutorial will walk you through appmapping of a popular opensource application `chipy.org` implemented in Python and Dango. You will map this application with the [AppMap for Visual Studio Code](
Is `appmapping` the capitalization we want? It looks funny with AppMap used everywhere else....

2021-02-24 22:43 UTC, ptrdvrk commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +This tutorial will walk you through appmapping of a popular opensource application `chipy.org` implemented in Python and Dango. You will map this application with the [AppMap for Visual Studio Code](
Yes, let me make another quick pass at this, thank you @apotterri .

2021-02-24 22:57 UTC, dustinbyrne reviewed
Some inconsistencies worth fixing:

- `s/VSCode studio/Visual Studio Code/`
- `s/VSCode/Visual Studio Code/`
- `s/IDE/Visual Studio Code/`
- `s/docker/Docker/`
- `s/python/Python/` (unless referring to the binary)
- `s/opensource/open source/`

2021-02-24 22:57 UTC, dustinbyrne commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +
extra whitespace

2021-02-24 22:57 UTC, dustinbyrne commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +If you have encountered any problems during these steps, please consult the [installation guide](https://github.com/chicagopython/chipy.org#installation) or contact us on Discord (link at the bottom.
Link Discord here?

2021-02-24 22:57 UTC, dustinbyrne commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +This tutorial will walk you through appmapping of a popular opensource application `chipy.org` implemented in Python and Dango. You will map this application with the [AppMap for Visual Studio Code](
Nit-picky, but I wouldn't call chipy.org a popular open source application. Maybe 'exemplary'?

2021-02-24 23:00 UTC, ptrdvrk commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +If you have encountered any problems during these steps, please consult the [installation guide](https://github.com/chicagopython/chipy.org#installation) or contact us on Discord (link at the bottom.
I intentionally wanted them to scroll to the bottom to see the screenshot and the video. I can add the link though, no problem.

2021-02-24 23:37 UTC, apotterri requested changes
Another language change: `appmap` is a Python package, rather than a module.

2021-02-25 00:27 UTC, jaredKreppein commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +This tutorial will walk you through AppMapping of an open source application `chipy.org` implemented in Python and Dango. You will map this application with the [AppMap for Visual Studio Code](https:
"This tutorial will walk you through AppMapping of an open source application" -- this might sound awkward. Maybe remove `of` or add `the process of`
- "This tutorial will walk you through the process of AppMapping an open source application..."
- "This tutorial will walk you through AppMapping an open source application..."

2021-02-25 00:28 UTC, jaredKreppein commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +- Install the Visual Studio Code and the AppMap extension
"Install the Visual Studio Code application" or "Install Visual Studio Code"

2021-02-25 11:59 UTC, apotterri commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +The `appmap` package configuration is stored in an `appmap.yml` file in the root directory of Python projects. Create a new file called `appmap.yml` in the root folder of the `chipy.org` folder, and
> The file lists all packages and classes that will be recorded, in this example all objects in the `chipy_org` package:

should be 

> The file lists modules, classes, and functions that will be recorded, in this example all objects in the `chipy_org` module:

i.e. "module", not "package".

A package is the installable unit in python, the thing you get from PyPI and install using `pip`. A package contains modules, which are python's construct for organizing code within a package.

2021-02-25 11:59 UTC, apotterri commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
>  The format of `appmap.yml` is documented in the [appmap-python documentation](https://github.com/applandinc/appmap-python/blob/master/README.md). `appmap.yml` can be fine tuned to include/exclude ind
> individual packages, classes and methods

should be
> individual modules, classes, and methods

2021-02-25 12:07 UTC, apotterri requested changes
I've noted a couple of places where the correct python terminology is "module" rather than "package".

This leads to an unfortunate disconnect: the attribute in `appmap.yml` is `packages`, but the values for it are Python module names. (The values for the `path` attribute of `packages` are also modules, which sort of are and sort of aren't "paths".)

At some point, we may want to consider having `appmap.yml` to the conventions of the current language, rather than using Ruby's conventions.

2021-02-25 13:32 UTC, ptrdvrk commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
> +The `appmap` package configuration is stored in an `appmap.yml` file in the root directory of Python projects. Create a new file called `appmap.yml` in the root folder of the `chipy.org` folder, and
Thank you Alan. Fixing now.

2021-02-25 13:32 UTC, ptrdvrk commented on doc/TUTORIAL-PYTHON-CHIPYORG.md
>  The format of `appmap.yml` is documented in the [appmap-python documentation](https://github.com/applandinc/appmap-python/blob/master/README.md). `appmap.yml` can be fine tuned to include/exclude ind
Fixed.

2021-02-25 13:33 UTC, ptrdvrk commented
@jaredKreppein please see Alan's comments about the Python naming nomenclature for future documentation efforts.

2021-02-25 13:57 UTC, apotterri approved these changes

2021-02-25 14:15 UTC, merged