fix: Show AppMap instructions on extension first open
applandinc/vscode-appland pull request #164
Opened 2021-03-26 17:18 UTC by sashahonchar

Fixes: https://github.com/applandinc/appmap-js/issues/136

2021-03-29 18:55 UTC, dustinbyrne requested changes

2021-03-29 18:55 UTC, dustinbyrne commented on web/src/app.js
> +      vscode.setState({ text });
If you declare this in its own scope, you won't need to disable the `no-case-declarations` eslint rule. The worry is that a variable is initialized in one case, but then used in a following case and thus never initialized. Adding an explicit scope prevents this:

```js
case 'update':
  {
    const { text } = message;
    app.loadData(text);

    // Then persist state information.
    // This state is returned in the call to `vscode.getState` below when a webview is reloaded.
    vscode.setState({ text });
  }
  break;
```

2021-03-29 19:13 UTC, dustinbyrne commented
This will also require `@appland/appmap` is upgraded to `v1.10.1`. We've been bumping versions as `fix`. Please let me know if this introduces any issues, we did update some of the bundling between releases.

2021-03-30 14:26 UTC, typaulhus approved these changes

2021-04-06 21:45 UTC, merged