feat: upload AppMap to AppLand server
applandinc/vscode-appland pull request #182
Opened 2021-05-08 11:54 UTC by artemvaskoo

**First version of AppMap Uploader**

For test purpose, I had to change `appmap` dependency to be loaded from a local file, as there's no released version yet.

When running `npm install`, remove `node_modules/@appland/appmap` if you encounter installation errors, as it apparently cannot be replaced by a symlink automatically.

After uploading, it displays a notification and opens a browser window, where the uploaded data is collected and added to the user profile. For that to work, you have to use `feature/vscode-upload-handling` branch for AppLand from `Appmap-server` PR#863(https://github.com/applandinc/appmap-server/pull/863) and change `appMap.appLandURL` configuration value to point to your local instance.

2021-05-08 12:20 UTC, kgilpin commented on src/appmapUploader.ts
> +          headers: { 'X-Requested-With': 'VSCodeUploader' },
I suggest instead to post the data to an /api route. That will make sense for this flow, and to get a JSON response. It will also be more clear to document.

2021-05-08 15:57 UTC, artemvaskoo commented on src/appmapUploader.ts
> +          headers: { 'X-Requested-With': 'VSCodeUploader' },
Okay I will change

2021-05-08 15:58 UTC, sashahonchar approved these changes

2021-05-08 16:43 UTC, dustinbyrne commented on package.json
> +    "@appland/appmap": "file:../appmap-js",
You can use `npm link` to avoid this
https://docs.npmjs.com/cli/v7/commands/npm-link

2021-05-08 16:49 UTC, dustinbyrne commented on package.json
> +    "axios": "^0.21.1",
This is a bit nit-picky, but we've included [`bent`](https://www.npmjs.com/package/bent) for making HTTP requests. Do we need this dependency?

2021-05-25 19:50 UTC, dustinbyrne requested changes

2021-05-25 19:50 UTC, dustinbyrne commented on package.json
> +        "appMap.appLandURL": {
Can we rename this key to `appmap.serverURL`?

2021-05-28 00:01 UTC, artemvaskoo commented
Updated with telemetry and confirmation

Currently, the confirmation button works globally and will allow any `appmap` to be uploaded after the first one is confirmed. It will need more time to develop if we want to add per-file confirmation.

2021-05-28 01:34 UTC, kgilpin commented
Once seems fine to me

On Thu, May 27, 2021 at 8:02 PM artemvaskoo ***@***.***>
wrote:

> Updated with telemetry and confirmation
>
> Currently, the confirmation button works globally and will allow any
> appmap to be uploaded after the first one is confirmed. It will need more
> time to develop if we want to add per-file confirmation.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/vscode-appland/pull/182#issuecomment-850017968>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC64VY3IWPVBQ6JY6UXTTP3MQJANCNFSM44MW24TA>
> .
>

2021-05-28 16:08 UTC, kgilpin commented
Or simply upload to default URL https://app.land

On Fri, May 28, 2021 at 11:30 AM Sasha H. ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/appmapUploader.ts
> <https://github.com/applandinc/vscode-appland/pull/182#discussion_r641638721>
> :
>
> > +    const configUrl: string = vscode.workspace
> +      .getConfiguration('appMap')
> +      .get('serverURL') as string;
> +    return vscode.Uri.parse(configUrl);
>
> When user removes URL of AppLand Server settings this line returns
> 'file:///' string and bent throws an error:
>
> Error: Unknown encoding, file:///
>
> I think we should handle empty URL in user configuration and show error
> notification.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/vscode-appland/pull/182#pullrequestreview-671421233>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC66CHTUB4M6VHZ4TPMTTP6ZJBANCNFSM44MW24TA>
> .
>

2021-05-28 16:26 UTC, sashahonchar commented
I don't think it's a good idea to hard-code server URL. @kgilpin 
It's better to show an error notification when URL settings is empty. https://github.com/applandinc/vscode-appland/pull/182/commits/15e5cd5adb199af3e5f260a7714cc808e7d69666

2021-05-28 17:12 UTC, kgilpin commented
Why would we require the user to enter a setting which is the same for 99%
of users?

On Fri, May 28, 2021 at 12:26 PM Sasha H. ***@***.***> wrote:

> I don't think it's a good idea to hard-code server URL. @kgilpin
> <https://github.com/kgilpin>
> It's better to show an error notification when URL settings is empty.
> 15e5cd5
> <https://github.com/applandinc/vscode-appland/commit/15e5cd5adb199af3e5f260a7714cc808e7d69666>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/vscode-appland/pull/182#issuecomment-850532176>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC6ZX2RYPNMEZMU57OILTP672ZANCNFSM44MW24TA>
> .
>

2021-05-28 20:39 UTC, sashahonchar commented
I agree, when user setting is empty it's better to use https://app.land as default server. 
https://github.com/applandinc/vscode-appland/pull/182/commits/3cbff63bd5b39867bddbe64f71261836f072f457

2021-05-29 17:51 UTC, artemvaskoo commented
> Why would we require the user to enter a setting which is the same for 99% of users?
It should not be empty unless it's manually set to empty, because there's a default value for it in `package.json`

2021-08-06 19:25 UTC, dustinbyrne approved these changes

2021-08-06 19:30 UTC, merged

2021-08-06 19:39 UTC, appland-release commented
:tada: This PR is included in version 0.17.0 :tada:

The release is available on:
- `v0.17.0`
- [GitHub release](https://github.com/applandinc/vscode-appland/releases/tag/v0.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: