feat: remote recording commands
applandinc/vscode-appland pull request #183
Opened 2021-05-12 14:57 UTC by sashahonchar

Fixes: #177 
Fixes: https://github.com/applandinc/appmap-js/issues/201

2021-05-17 18:43 UTC, dustinbyrne requested changes
Looking good! I left a few comments.

2021-05-17 18:43 UTC, dustinbyrne commented on src/remoteRecording.ts
> +  static async getStatus(): Promise<void> {
Can we split up the HTTP client from the VSCode logic to keep things flexible?

I'd expect the HTTP client to be fit into or be similar to one of the following interfaces:
```ts
interface RecordingClient {
  url: string;

  start(): Promise<void>;
  stop(): Promise<string>;
  status(): Promise<Record<string, unknown>>;
}
```

e.g.:
```ts
const client = new MyRecordingClient('https://localhost:3001');
await client.start();

// ...

const appmap = buildAppMap(await client.stop()).build();
```

Alternatively, as static methods as you currently have it implemented. This probably makes the most sense for this use case. Bonus points for [maintaining functional style](https://www.gamasutra.com/view/news/169296/Indepth_Functional_programming_in_C.php).
```ts
interface RecordingClient {
  start(url: string): Promise<void>;
  stop(url: string): Promise<string>;
  status(url: string): Promise<Record<string, unknown>>;
}
```

The rest of the VSCode logic (`showInputBox`, `showInformationMessage`, etc.) can exist in the command definition.

2021-05-17 18:43 UTC, dustinbyrne commented on src/remoteRecording.ts
> +      const document = await vscode.workspace.openTextDocument({
I'd like to immediately pop open the AppMap viewer. Any ideas?

An easy fix would be to save the file to disk. Alternatively, a [`TextDocumentContentProvider`](https://code.visualstudio.com/api/extension-guides/virtual-documents#textdocumentcontentprovider) could also work, if the URI ends with `.appmap.json`. Stopping the recording would instead open a file using a custom scheme (something like `appmap-remote://https%3A%2F%2Flocalhost:3000.appmap.json`) which parses the URI, issues a stop request to the endpoint, and returns the JSON document as a `string`.

I'm sure I've left out some details, so please reach out with questions if you'd like some help with this.

2021-05-18 21:42 UTC, sashahonchar commented on src/remoteRecording.ts
> +  static async getStatus(): Promise<void> {
It's not possible to create an object definition like this:
```javascript
const client = new MyRecordingClient('https://localhost:3001');
await client.start();
// ...
const appmap = buildAppMap(await client.stop()).build();
```
The reason is we will ask user for server URL before every command execution.

2021-05-18 21:52 UTC, sashahonchar commented on src/remoteRecording.ts
> +    const request = bent('http://' + baseURL, 'DELETE', 'json', 200);
Done https://github.com/applandinc/vscode-appland/pull/183/commits/d81689abff5c3e47f4c9ca9fe2ba07a932e532ae

2021-05-18 21:53 UTC, sashahonchar commented on src/remoteRecording.ts
> +    const request = bent('http://' + baseURL, 'POST', 'json', 200);
Done https://github.com/applandinc/vscode-appland/pull/183/commits/6b2744f7e854816acb4d5e77ef938bb36d38946c

2021-05-18 22:36 UTC, dustinbyrne commented on src/remoteRecording.ts
> +  static async getStatus(): Promise<void> {
Sorry, the example I gave is confusing. I don't expect to start/stop in the same block. I'm advocating for separation of the HTTP client and VS code interaction logic:

```ts
context.subscriptions.push(
  vscode.commands.registerCommand('appmap.startRemoteRecording', () => {
    const baseURL = (await getBaseUrl()) || '';
    if (baseURL === '') {
      return;
    }

    try {
      RemoteRecording.start(baseURL);
      vscode.window.showInformationMessage(`Recording started at "${baseURL}"`);
    } catch (e) {
      vscode.window.showErrorMessage(`Start recording failed: ${e.name}: ${e.message}`);
    }
  })
);
```

2021-05-19 17:07 UTC, dustinbyrne requested changes
Hi @sashahonchar, I have a few more items that came up earlier today.

- Upon stopping the recording, prompt the user to name the AppMap. This should set the `metadata.name` property before saving the file out or displaying it in the editor.
- A status bar indicator should be present while a recording is in progress. Clicking the indicator stops the recording and prompts the user to enter a name. This action should be able to be cancelled, and the recording continued.
- A history of service URLs saved per-workspace. As a user, I don't want to have to re-enter my service URL every time I start a recording. The user can either type in a service URL or select a previous service URL from a list. The history is unique to the current workspace path.
- A button is added to the AppMap panel to start a new recording. Other button definitions are found here: https://github.com/applandinc/vscode-appland/blob/master/package.json#L116-L125

2021-05-19 18:13 UTC, kgilpin commented
When the new AppMap is saved, it should also be processed with the Indexer,
so that it can be efficiently searched and compared.

On Wed, May 19, 2021 at 1:07 PM Dustin Byrne ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @sashahonchar <https://github.com/sashahonchar>, I have a few more
> items that came up earlier today.
>
>    - Upon stopping the recording, prompt the user to name the AppMap.
>    This should set the metadata.name property before saving the file out
>    or displaying it in the editor.
>    - A status bar indicator should be present while a recording is in
>    progress. Clicking the indicator stops the recording and prompts the user
>    to enter a name. This action should be able to be cancelled, and the
>    recording continued.
>    - A history of service URLs saved per-workspace. As a user, I don't
>    want to have to re-enter my service URL every time I start a recording. The
>    user can either type in a service URL or select a previous service URL from
>    a list. The history is unique to the current workspace path.
>    - A button is added to the AppMap panel to start a new recording.
>    Other button definitions are found here:
>    https://github.com/applandinc/vscode-appland/blob/master/package.json#L116-L125
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/vscode-appland/pull/183#pullrequestreview-663462428>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC66IAXBA7WP6KMLVNRDTOPV5VANCNFSM44YY5QCA>
> .
>

2021-05-19 18:18 UTC, kgilpin commented
I guess you can shell out to the index CLI command to do this.

On Wed, May 19, 2021 at 2:13 PM Kevin Gilpin ***@***.***> wrote:

> When the new AppMap is saved, it should also be processed with the
> Indexer, so that it can be efficiently searched and compared.
>
> On Wed, May 19, 2021 at 1:07 PM Dustin Byrne ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hi @sashahonchar <https://github.com/sashahonchar>, I have a few more
>> items that came up earlier today.
>>
>>    - Upon stopping the recording, prompt the user to name the AppMap.
>>    This should set the metadata.name property before saving the file out
>>    or displaying it in the editor.
>>    - A status bar indicator should be present while a recording is in
>>    progress. Clicking the indicator stops the recording and prompts the user
>>    to enter a name. This action should be able to be cancelled, and the
>>    recording continued.
>>    - A history of service URLs saved per-workspace. As a user, I don't
>>    want to have to re-enter my service URL every time I start a recording. The
>>    user can either type in a service URL or select a previous service URL from
>>    a list. The history is unique to the current workspace path.
>>    - A button is added to the AppMap panel to start a new recording.
>>    Other button definitions are found here:
>>    https://github.com/applandinc/vscode-appland/blob/master/package.json#L116-L125
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/applandinc/vscode-appland/pull/183#pullrequestreview-663462428>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AAAVC66IAXBA7WP6KMLVNRDTOPV5VANCNFSM44YY5QCA>
>> .
>>
>

2021-05-19 22:36 UTC, sashahonchar commented on src/remoteRecording.ts
> +  static async getStatus(): Promise<void> {
Done https://github.com/applandinc/vscode-appland/pull/183/commits/2bdf340efbf2010166c5245dcb69a059c819f61a

2021-05-24 16:49 UTC, dustinbyrne commented on src/extension.ts
> +        vscode.window.showErrorMessage(`Start recording failed: ${e.name}: ${e.message}`);
This should also clear state. Otherwise, we cannot try again.
```js
remoteURL = null;
```

2021-05-24 16:49 UTC, dustinbyrne commented on src/extension.ts
> +        RemoteRecording.start(remoteURL);
This call requires `await`, otherwise an exception will never be handled in this scope.

2021-05-24 16:49 UTC, dustinbyrne commented on package.json
>            "group": "navigation@0"
Can we add a `when` condition to display a stop command if a recording is already in progress?

2021-05-25 16:22 UTC, dustinbyrne commented
I found a method for displaying an input box with an optional pre-populated item selection. 

```js
import * as vscode from 'vscode';

export default class QuickPickHistory {
  public static async open(): Promise<string> {
    const quickPick = vscode.window.createQuickPick();

    // Add historical endpoints here
    quickPick.items = [{ label: 'a' }, { label: 'b' }, { label: 'c' }];

    // Configure the rest of the input box (placeholder, etc.) 

    return new Promise((resolve) => {
      quickPick.show();
      quickPick.onDidAccept((e) => {
        // If no label is selected, fall back to the input value instead
        console.log(quickPick.selectedItems[0]?.label, quickPick.value);
        resolve(quickPick.selectedItems[0]?.label || quickPick.value);
      });
    });
  }
}
```

2021-06-02 20:51 UTC, sashahonchar commented
Fixes: #201

2021-06-07 19:59 UTC, dustinbyrne approved these changes

2021-06-07 20:01 UTC, merged