feat: Telemetry `install` event
applandinc/vscode-appland pull request #233
Opened 2021-06-10 15:43 UTC by sashahonchar

2021-06-10 21:22 UTC, dustinbyrne requested changes

2021-06-10 21:22 UTC, dustinbyrne commented on src/extension.ts
> +    Telemetry.reportAction('appland.appmap/plugin:install', undefined);
`appland.appmap/` is prepended by the library. The first argument only needs to be `plugin:install`.

2021-06-12 12:21 UTC, sashahonchar commented on src/extension.ts
> +    Telemetry.reportAction('appland.appmap/plugin:install', undefined);
Done https://github.com/applandinc/vscode-appland/pull/233/commits/d68ea06d9ff367a98352b22ce800e494eb690326

2021-07-28 21:31 UTC, dustinbyrne approved these changes

2021-07-28 21:31 UTC, merged