WIP:  Quick start auto-open after init
applandinc/vscode-appland pull request #276
Opened 2021-07-15 19:43 UTC by ptrdvrk

2021-07-16 14:28 UTC, apotterri commented on src/tree/milestoneTreeDataProvider.ts
> +  public getParent(): Thenable<vscode.TreeItem | null> {
Is this necessary? It doesn't seem like it's doing much....

2021-07-16 14:31 UTC, ptrdvrk commented on src/tree/milestoneTreeDataProvider.ts
> +  public getParent(): Thenable<vscode.TreeItem | null> {
Without this the milestoneTree.reveal() in extension.ts does not work, errors on missing function getParent().

2021-07-16 14:41 UTC, apotterri requested changes
The two commits in this PR should get squashed together, which could be done when the PR gets merged. However, they have different semantic release prefixes. Which is correct?

2021-07-16 14:41 UTC, apotterri commented on src/tree/milestoneTreeDataProvider.ts
> +  public getParent(): Thenable<vscode.TreeItem | null> {
Do you understand why that is? Why wasn't it necessary before your change?

2021-07-16 15:09 UTC, ptrdvrk reviewed
> The two commits in this PR should get squashed together, which could be done when the PR gets merged. However, they have different semantic release prefixes. Which is correct?

The second commit with the "misc:" prefix just updated the comments. It can be removed.

2021-07-16 17:34 UTC, apotterri approved these changes

2021-07-16 17:34 UTC, merged

2021-07-30 22:34 UTC, appland-release commented
:tada: This PR is included in version 0.15.0 :tada:

The release is available on:
- `v0.15.0`
- [GitHub release](https://github.com/applandinc/vscode-appland/releases/tag/v0.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: