feat: user terminal
applandinc/vscode-appland pull request #294
Opened 2021-07-21 19:11 UTC by sashahonchar

2021-07-21 20:16 UTC, kgilpin commented on src/terminal/index.ts
> +    const echoStatus = 'echo $? > ' + this.baseDir + 'exitStatus';
How about using `fs.join` here?

2021-07-21 20:17 UTC, kgilpin commented on src/agent/appMapAgentRuby.ts
> +      console.log(e);
Can/should this be directed to a VSCode output?

2021-07-21 20:18 UTC, kgilpin commented
@sashahonchar you'll probably want to clean up the history before merging.

2021-07-21 21:13 UTC, sashahonchar commented on src/agent/appMapAgentRuby.ts
> +      console.log(e);
Error message will be displayed on Quickstart webview:
https://github.com/applandinc/vscode-appland/blob/7868c2069be47775bbeeb3bdf7dc7c62eeba3b54/src/agent/appMapAgentRuby.ts#L96

2021-07-21 21:16 UTC, sashahonchar commented on src/terminal/index.ts
> +    const echoStatus = 'echo $? > ' + this.baseDir + 'exitStatus';
Done https://github.com/applandinc/vscode-appland/pull/294/commits/6eb052092ee5a995529d3f1fff62ca54ae0df846

2021-07-21 21:16 UTC, sashahonchar commented
> @sashahonchar you'll probably want to clean up the history before merging.

Done. I squashed 'wip' commits into this one https://github.com/applandinc/vscode-appland/pull/294/commits/fd7d8ec02c444498a2b98ab162d5b35b52bf94af

2021-07-22 12:30 UTC, kgilpin requested changes
I think it's good that we did this exercise but we need to hold off on replacing the existing flow with this flow for all situations. 

Also, chokidar should be removed and replaced with the built in VSCode file watcher. Native code is not allowed in VSCode extensions.

2021-07-26 17:00 UTC, torchello commented
Closing this for now.

2021-07-26 17:00 UTC, closed without merging