feat: Add `config:write` event
applandinc/vscode-appland pull request #319
Opened 2021-08-04 23:11 UTC by torchello

2021-08-05 16:44 UTC, dustinbyrne requested changes
Looking good! I've added a few minor comments below. 👍

2021-08-05 16:44 UTC, dustinbyrne commented on src/telemetry/definitions/properties.ts
> +  async value({ agent, rootDirectory }: { agent?: AppMapAgent; rootDirectory: PathLike }) {
Could this optionally take either:
- a `Uri` of the config so that it may parse the `app` name if `agent` is unavailable
- a JSON representation of the config to do the same
- a `name: string` override, where it'll just return the `name` argument if it's supplied

My concern is that the agent won't be available to provide this information.

2021-08-05 16:44 UTC, dustinbyrne commented on src/telemetry/definitions/properties.ts
> +    try {
If `agent` is `undefined`, return `undefined`.  If the agent is unavailable, we can't reason about whether the file is valid without performing the validation logic ourselves here. Returning `undefined` will omit this property from the telemetry event, instead of reporting an invalid config.

2021-08-05 16:44 UTC, dustinbyrne commented on src/telemetry/definitions/properties.ts
> +    return fs
Prefer `await` with a try/catch. I believe this will return a `Promise<Promise<string>>`, and I'm not certain that'll be properly handled. I wouldn't worry about whether an entity at the given URI exists  or not, report the path nonetheless. For example, if we're describing a file that's deleted, knowing the path of the file is more useful than reporting the path as `deleted`.

2021-08-05 16:44 UTC, dustinbyrne commented on src/telemetry/definitions/properties.ts
> +    return fs
Prefer `await`. Similar to above, this will return a `Promise<Promise<string>>`, which may not perform as intended. If an error occurs, return `undefined` and omit this property from the telemetry event altogether.

2021-08-05 16:44 UTC, dustinbyrne commented on src/telemetry/definitions/properties.ts
> +    return fs
Prefer `await`. The `access` call seems redundant, because we're calling `readFile` next, which will raise an exception if the file doesn't exist.

Please return `undefined` on error to omit this property from the telemetry event data instead of reporting an empty string.

2021-08-05 16:44 UTC, dustinbyrne commented on src/projectWatcher.ts
> +    configWatcher.onDidDelete(configWatcherListener);
Delete should send a `project/config:delete` event

2021-08-09 18:10 UTC, torchello commented on src/projectWatcher.ts
> +    configWatcher.onDidDelete(configWatcherListener);
We'll handle `onDidDelete` separately then.

2021-08-09 18:10 UTC, torchello commented on src/telemetry/definitions/properties.ts
> +  async value({ agent, rootDirectory }: { agent?: AppMapAgent; rootDirectory: PathLike }) {
Updated!

2021-08-10 20:55 UTC, dustinbyrne approved these changes

2021-08-10 20:56 UTC, merged