fix: Handle invalid git ignore globs gracefully
applandinc/vscode-appland pull request #327
Opened 2021-08-16 21:53 UTC by dustinbyrne

2021-08-16 22:41 UTC, torchello commented
Agree with @kgilpin. If don't need this exceptions for analytics (I guess we don't) we can just silently skip.

2021-08-16 22:46 UTC, kgilpin requested changes

2021-08-16 22:46 UTC, kgilpin commented on src/telemetry/properties/versionControlGit.ts
> +        Telemetry.sendEvent(DEBUG_EXCEPTION, { exception });
Exception should be verified as being the expected type, and not sent to telemetry.

2021-08-17 16:13 UTC, dustinbyrne commented
I'd like to know what pattern is raising an exception, because I see no reason we should be failing here. With that data, we can issue a proper fix.

2021-08-17 16:52 UTC, dustinbyrne commented
I'll address this in a different manner that replaces `globToRegExp` outright.

2021-08-17 16:52 UTC, closed without merging