Telemetry events
applandinc/vscode-appland pull request #328
Opened 2021-08-17 16:39 UTC by sashahonchar

Implemented telemetry events:
- appmap:upload
- remote_recording:start
- remote_recording:stop
- remote_recording:status

Fixes #314 
Fixes #266  
Fixes #211
Fixes #212 
Fixes #213 
Fixes #214 
Fixes #215 
Fixes #216

2021-08-17 18:52 UTC, torchello approved these changes
LGTM

2021-08-23 21:53 UTC, dustinbyrne requested changes

2021-08-23 21:53 UTC, dustinbyrne commented on src/remoteRecordingClient.ts
> +    });
[`PROJECT_LANGUAGE` is listed in this event type](https://github.com/applandinc/vscode-appland/blob/341c788837a07ac6cc0f408a25d2afe9b6ad5e45/src/telemetry/definitions/events.ts#L80), but has no way of being resolved when the event is sent. Try specifying `rootDirectory` here, containing the root directory of the workspace folder / project. [See the data resolver method for `PROJECT_LANGUAGE` here.](https://github.com/applandinc/vscode-appland/blob/341c788837a07ac6cc0f408a25d2afe9b6ad5e45/src/telemetry/definitions/properties.ts#L96)

2021-08-23 21:53 UTC, dustinbyrne commented on src/remoteRecordingClient.ts
> +    });
[`PROJECT_LANGUAGE` is listed in this event type](https://github.com/applandinc/vscode-appland/blob/341c788837a07ac6cc0f408a25d2afe9b6ad5e45/src/telemetry/definitions/events.ts#L89), but has no way of being resolved when the event is sent. Try specifying `rootDirectory` here, containing the root directory of the workspace folder / project. [See the data resolver method for `PROJECT_LANGUAGE` here.](https://github.com/applandinc/vscode-appland/blob/341c788837a07ac6cc0f408a25d2afe9b6ad5e45/src/telemetry/definitions/properties.ts#L96)

2021-08-23 21:53 UTC, dustinbyrne commented on src/remoteRecordingClient.ts
> +    });
[`PROJECT_LANGUAGE` is listed in this event type](https://github.com/applandinc/vscode-appland/blob/341c788837a07ac6cc0f408a25d2afe9b6ad5e45/src/telemetry/definitions/events.ts#L71), but has no way of being resolved when the event is sent. Try specifying `rootDirectory` here, containing the root directory of the workspace folder / project. [See the data resolver method for `PROJECT_LANGUAGE` here.](https://github.com/applandinc/vscode-appland/blob/341c788837a07ac6cc0f408a25d2afe9b6ad5e45/src/telemetry/definitions/properties.ts#L96)

2021-08-23 21:53 UTC, dustinbyrne commented on web/src/appmapView.js
> +      metrics: getAppMapMetrics(app.$refs.$store.state.appMap),
This is failing for me. See attached screenshot. 
![image](https://user-images.githubusercontent.com/8737782/130524343-cd28d6f9-0e71-4c3c-b464-ac3e87017395.png)

2021-08-24 12:03 UTC, sashahonchar commented on src/remoteRecordingClient.ts
> +    });
Done https://github.com/applandinc/vscode-appland/pull/328/commits/b543425e131b669f98708973111e93cc34a1fdf8

2021-08-24 12:03 UTC, sashahonchar commented on src/remoteRecordingClient.ts
> +    });
Done https://github.com/applandinc/vscode-appland/pull/328/commits/b543425e131b669f98708973111e93cc34a1fdf8

2021-08-24 12:03 UTC, sashahonchar commented on src/remoteRecordingClient.ts
> +    });
Done https://github.com/applandinc/vscode-appland/pull/328/commits/b543425e131b669f98708973111e93cc34a1fdf8

2021-08-24 12:03 UTC, sashahonchar commented on web/src/appmapView.js
> +      metrics: getAppMapMetrics(app.$refs.$store.state.appMap),
Fixed https://github.com/applandinc/vscode-appland/pull/328/commits/d870daa8d791f36eb8e954e1f7f31ad24cc309c6

2021-08-24 14:47 UTC, dustinbyrne requested changes

2021-08-24 14:47 UTC, dustinbyrne commented on src/remoteRecordingClient.ts
> +    }
Thank you for doing this. This code is problematic too, in that the user may have more than one folder in the workspace, and this may or may not be the correct root directory. This highlights the fact that the `language` property just isn't resolvable from these remote recording events.

Sorry to be a pain, but can we drop this commit and remove [`Properties.PROJECT_LANGUAGE`](https://github.com/applandinc/vscode-appland/pull/328/files#diff-d36eda4e750b98c92d2c8b6b0af52220a85553164cb12b119da017dc42228eb4R71) from the recording status commands? Ideally, if we were to re-add it, the recording API would be the source of truth for this kind of information.

2021-08-24 17:09 UTC, sashahonchar commented on src/remoteRecordingClient.ts
> +    }
Done https://github.com/applandinc/vscode-appland/pull/328/commits/93e9cdbbc8c0caa4c8d6b64e72c8c6f13c10f275

2021-08-24 17:21 UTC, dustinbyrne approved these changes

2021-09-02 22:14 UTC, merged

2021-09-07 19:07 UTC, appland-release commented
:tada: This PR is included in version 0.18.0 :tada:

The release is available on:
- `v0.18.0`
- [GitHub release](https://github.com/applandinc/vscode-appland/releases/tag/v0.18.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: