fix: remove 'glob-to-regexp' dependency and use 'ignore'
applandinc/vscode-appland pull request #334
Opened 2021-08-19 16:08 UTC by sashahonchar

Fixes: #333

2021-08-19 16:54 UTC, dustinbyrne requested changes

2021-08-19 16:54 UTC, dustinbyrne commented on src/telemetry/properties/versionControlGit.ts
> +    return this.ignore.ignores(path as string);
`path` is guaranteed (?) to be absolute, so this check will always fail. I think we'll need to keep track of the absolute base path of each `.gitignore`, then pick the right `ignore` object to check against.

Example:
Given the following lookup table of git ignores,
``js
{
  '/home/db/dev/applandinc/appmap': ignore(),
  '/home/db/dev/applandinc/appmap/some/directory': ignore(),
}
```

and a call to `isIgnored` with the `path` defined as `/home/db/dev/applandinc/appmap/node_modules`, the first value in the lookup table is used. The basename is subtracted from the path, resulting in `node_modules`, and that value is checked for ignore.

If `path` is `/home/db/dev/applandinc/appmap/some/directory/file.txt`, the second value in the lookup table is chosen because it matches more of the path than the first.

2021-08-20 16:52 UTC, sashahonchar commented on src/telemetry/properties/versionControlGit.ts
> +    return this.ignore.ignores(path as string);
Good point, thanks @dustinbyrne 
I made changes and now we'll find all known `.gitignore` files recursively to the root folder and check is needed file ignored in any of those gitignores. https://github.com/applandinc/vscode-appland/pull/334/commits/197531085ba7c3df911213a8ba15d06367741876

2021-08-23 21:06 UTC, dustinbyrne approved these changes

2021-09-02 22:15 UTC, merged

2021-09-07 19:07 UTC, appland-release commented
:tada: This PR is included in version 0.18.0 :tada:

The release is available on:
- `v0.18.0`
- [GitHub release](https://github.com/applandinc/vscode-appland/releases/tag/v0.18.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: