chore: js+express supported
applandinc/vscode-appland pull request #369
Opened 2021-12-08 19:46 UTC by ptrdvrk

2021-12-13 21:21 UTC, apotterri requested changes

2021-12-13 21:21 UTC, apotterri commented on package.json
> +    "js"
If understand this correctly, these are the tags that get displayed here, right?
![image](https://user-images.githubusercontent.com/4212483/145890274-a00dfda0-c3ce-4daa-a96f-02d7b683d7e9.png)

I tried searching for `tag:js`, and got basically useless results. `tag:javascript` was much better, so I wonder if there's value in including `js` here? OTOH, `tag: typescript` *was* useful, so maybe `typescript` should be included in this list?

2021-12-13 22:00 UTC, ptrdvrk commented on package.json
> +    "js"
OK, let's change `js` to `typescript`, good call. According to the docs, only 5 tags are permitted but just like many other things on the marketplace, the manifest works with more (mysteriously).

https://code.visualstudio.com/api/references/extension-manifest

2021-12-13 22:22 UTC, apotterri approved these changes

2021-12-13 22:49 UTC, merged

2022-01-12 23:17 UTC, appland-release commented
:tada: This PR is included in version 0.23.1 :tada:

The release is available on:
- `v0.23.1`
- [GitHub release](https://github.com/applandinc/vscode-appland/releases/tag/v0.23.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: