Fix: show python and js as open beta
applandinc/vscode-appland pull request #422
Opened 2022-06-28 20:57 UTC by ahtrotta

Fixes applandinc/board#86

Change messages that get displayed in project picker. Show that Python and JavaScript are in Open Beta. Remove Python feature flag.

2022-06-29 00:59 UTC, brikelly reviewed
I haven't vetted the code or behavior, but the message strings all look like good edits.

2022-06-30 15:30 UTC, apotterri requested changes
Code changes look good here. Behavior should get tested by the new project picker tests, right @ahtrotta?

This needs a rebase before it can be merged. If you do it as an interactive rebase, you can reword the commit subject lines to include a commit type: 
![image](https://user-images.githubusercontent.com/4212483/176717045-81a0e8ad-0ee5-41a4-b15a-5f529d592679.png)

2022-06-30 18:23 UTC, apotterri approved these changes

2022-06-30 18:23 UTC, merged

2022-06-30 18:58 UTC, appland-release commented
:tada: This PR is included in version 0.32.2 :tada:

The release is available on:
- `v0.32.2`
- [GitHub release](https://github.com/applandinc/vscode-appland/releases/tag/v0.32.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: