Fix/investigate findings green check
applandinc/vscode-appland pull request #433
Opened 2022-07-07 17:40 UTC by ahtrotta

Fixes applandinc/board#57

The green check mark next to `Investigate findings` now appears when a user presses the 'View problems' button or when a user clicks on a tree item in the `Runtime Analysis` tree view.

2022-07-07 20:16 UTC, dustinbyrne commented on package.json
>        {
This command doesn't look to be intended to be used by an end-user, so we shouldn't include it here. The command definitions here are added to the command palette. It's not necessary to add an entry here when creating a new command via the API (i.e. `vscode.commands.registerCommand`).

2022-07-07 20:30 UTC, dustinbyrne commented on src/util.ts
> +
I'm not sure this is working as intended.

`path` will be something like `file:///home/user/my-project/app/controllers/posts_controller.rb`. It will never be equal to the project path. This is only working because upon hitting the first `await`, a promise is returned and `find` will return the first element in the `projectStates` array due to the truthy return value (a promise).

2022-07-07 21:08 UTC, ahtrotta commented on src/util.ts
> +
Interestingly, they are the same in my environment. But if they're not the same on Mac or Windows, then I definitely need to change this logic. Perhaps I should use a RegEx match?

![image](https://user-images.githubusercontent.com/45714532/177871516-3507ddba-d611-478b-a45d-32f0f577ea7d.png)

2022-07-07 21:11 UTC, ahtrotta commented on src/util.ts
> +
Ah, I discovered that they're the same when I click on the `View problems` button, but not when I click on a findings Tree item. I'll fix this up.

2022-07-08 14:01 UTC, ahtrotta commented on src/util.ts
> +
Okay, so I revamped this function. I modified it so that it uses `Promise.all` to avoid always returning the first element in the `projectStates` array. I also check if the `path` parameter includes the the `path` from the `projectState`, because something like `file:///home/user/my-project/app/controllers/posts_controller.rb` will contain `/home/user/my-project/` as a substring.

2022-07-08 14:25 UTC, ahtrotta commented on src/extension.ts
> +    }
Yup, good idea

2022-07-08 19:58 UTC, apotterri requested changes
It doesn't seem like the commits in this PR should be separate -- the same files are touched by many of them, and the comments only have (not very helpful) subject lines.

If they're all work towards the same end-goal, they should get combined into a single commit with a descriptive comment. (i.e. don't just squash them and that the subjects). If they got split up as a result of evolution during the review process, you should consider using [fixup commits](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---fixupamendrewordltcommitgt). These make it easy to clean things up using the [auto-squash](https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---autosquash) switch when doing a final rebase.

2022-07-08 20:19 UTC, kgilpin commented
Seconded

On Fri, Jul 8, 2022 at 3:58 PM Alan Potter ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> It doesn't seem like the commits in this PR should be separate -- the same
> files are touched by many of them, and the comments only have (not very
> helpful) subject lines.
>
> If they're all work towards the same end-goal, they should get combined
> into a single commit with a descriptive comment. (i.e. don't just squash
> them and that the subjects). If they got split up as a result of evolution
> during the review process, you should consider using fixup commits
> <https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---fixupamendrewordltcommitgt>.
> These make it easy to clean things up using the auto-squash
> <https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---autosquash>
> switch when doing a final rebase.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/applandinc/vscode-appland/pull/433#pullrequestreview-1033332601>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVC67D2QA22NVHUCL5LRDVTCB7HANCNFSM526HGEVQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-07-11 18:03 UTC, ahtrotta commented
Okay, I squashed all of the commits into one commit and tried (hopefully successfully, but let me know if not) to make a better commit message

2022-07-11 20:30 UTC, apotterri requested changes
This looks much better, thanks. A couple more minor changes:

* Because the comments on a PR more or less disappear once it gets merged, this should go on the commit, rather than the PR:
> The green check mark next to Investigate findings now appears when a user presses the 'View problems' button or when a user clicks on a tree item in the Runtime Analysis tree view.

* the subject line of the commit should be shorter than 72 characters, ideally [not more than 50](https://cbea.ms/git-commit/#limit-50):
<img width="691" alt="image" src="https://user-images.githubusercontent.com/4212483/178331832-7040a40d-a6a1-44e6-9284-bff4f23b6d4c.png">

2022-07-12 00:08 UTC, ahtrotta commented
I believe I addressed your comment, but let me know if it's not what you were looking for

2022-07-12 09:36 UTC, apotterri approved these changes

2022-07-12 15:22 UTC, merged