Systest 20220701
applandinc/vscode-appland pull request #437
Opened 2022-07-13 11:04 UTC by apotterri

2022-07-19 21:29 UTC, apotterri commented on test/system/tests/instructions.test.ts
> +  xit('hides the pending badge upon completing the installation steps', async function() {
This test is still being skipped, not so much because it's failing, but more because I couldn't figure out what it's supposed to be testing.

@ahtrotta Can you help me figure out what this is supposed to be doing, please?

2022-07-19 21:48 UTC, ahtrotta commented on test/system/tests/instructions.test.ts
> +  xit('hides the pending badge upon completing the installation steps', async function() {
Yeah, the `pending badge` is the little blue clock icon that is displayed on the AppMap extension icon. See here:
![image](https://user-images.githubusercontent.com/45714532/179854300-4c8d8a11-89c9-48e6-a9c3-7785af960dfc.png)

This test ensures that it disappears once a user completes all the instruction steps:
![image](https://user-images.githubusercontent.com/45714532/179854499-18287788-958e-4fac-ac6f-4791d7bd8d99.png)

2022-07-19 22:20 UTC, apotterri commented on test/system/tests/instructions.test.ts
> +  xit('hides the pending badge upon completing the installation steps', async function() {
Ah, ok, I understand now. I'll figure out how to make the test pass.

2022-07-20 12:15 UTC, apotterri commented on test/system/tests/instructions.test.ts
> +  xit('hides the pending badge upon completing the installation steps', async function() {
So, it looks like there are a couple of problems here: 
* the second call to `appMap.openActionPanel` closes it (suggesting that's it's name should actually be `toggleActionPanel`)
* the pending badge goes away when `appmap-findings.json` gets restored:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4212483/179979336-799a1be6-3148-4f57-aa05-1aa719e4e2ce.png">

The first is easily addressed, of course. But, is the second correct, or should the pending badge remain until the user has viewed the problem?

2022-07-20 19:34 UTC, apotterri commented on test/system/tests/instructions.test.ts
> +  xit('hides the pending badge upon completing the installation steps', async function() {
Hmmm, ok. It's definitely not working that way. So, it seems like there's really a problem here, but not one related to the reliability of the tests. We should open a separate issue to track it.

2022-07-21 00:33 UTC, ahtrotta requested changes
This looks good! There are only a few minor changes that I'd like to see (see comments). Definitely let me know if any of my comments are confusing or reveal that I'm misunderstanding something.

2022-07-21 00:33 UTC, ahtrotta commented on test/systemTest.ts
> +      await Promise.all([this.app.waitForEvent('close'), await this.app.close()]);
You don't need to use `await` inside of `Promise.all` since it's expecting an array of Promises.

2022-07-21 00:33 UTC, ahtrotta commented on test/unit/project.test.ts
> +      });
Missing an empty line after this line.

2022-07-21 00:33 UTC, ahtrotta commented on test/system/tests/instructions.test.ts
> +  it('displays a badge when AppMap installation is pending for an installable project', async function() {
Why did you switch from arrow functions to function declarations? (I'm not implying that you have to switch back to arrow functions. I just want to know for future reference.).

2022-07-21 09:06 UTC, apotterri commented on test/system/tests/instructions.test.ts
> +  it('displays a badge when AppMap installation is pending for an installable project', async function() {
I switched so I could use Mocha's context to store the driver and project. The context isn't available if you use arrow functions: https://mochajs.org/#arrow-functions .

2022-07-21 09:17 UTC, apotterri commented on extern/yarn.lock
> +  resolution: "@appland/components@npm:2.7.0"
Yarn is choosing the version of `@appland/components` here, based on the requirements of `@appland/appmap`. When `@appland/appmap` gets updated, we'll want to update the extension, too. (It's never, ever a good idea to update a lock file manually. You always want to let the package manager do it.)

2022-07-21 10:51 UTC, apotterri commented on test/system/src/app.ts
> +      process.env.INSPECT_EXTENSION ? '9229' : '',
Passing `--inspect-brk-extensions` when launching vscode is supposed to be a way to debug an extension. Port `9229` is the default port the debugger will connect to.

This appears to be broken in the latest Insider's build, though, so I've taken this setting out.

2022-07-21 10:51 UTC, apotterri commented on test/system/tests/instructions.test.ts
> +    await driver.appMap.assertInstructionStepStatus(
Fixed.

2022-07-21 10:54 UTC, apotterri commented on test/systemTest.ts
> -        case '--leave-open':
There is now a new instance of vscode being launched for every test case: https://github.com/applandinc/vscode-appland/pull/437/files#diff-40de7231596e00146a30b40f1ba91071ba798e4c4f1dd588e966546690bf4a84R57, so this switch no longer makes sense. To see what's happening in a test, you can run with a debugger attached.

2022-07-21 10:54 UTC, apotterri commented on test/unit/project.test.ts
> +      });
Fixed.

2022-07-21 10:54 UTC, apotterri commented on test/system/tests/support/project.ts
> +  // Prepare a new directory to become a copy the given project. It will be empty until reset is called.
Fixed.

2022-07-21 10:54 UTC, apotterri commented on test/systemTest.ts
> +      await Promise.all([this.app.waitForEvent('close'), await this.app.close()]);
Fixed.

2022-07-21 10:55 UTC, apotterri commented on test/system/tests/instructions.test.ts
> +  xit('hides the pending badge upon completing the installation steps', async function() {
@ahtrotta Can you open an issue for this, please?

2022-07-21 12:53 UTC, ahtrotta commented on test/system/tests/instructions.test.ts
> +  xit('hides the pending badge upon completing the installation steps', async function() {
Yup, I'll do that.

2022-07-21 12:55 UTC, dustinbyrne commented on test/system/tests/instructions.test.ts
>      await driver.instructionsWebview.getPageByTitle('Open AppMaps').waitFor();
Since the rebase, the `Open AppMaps` title in the webview appears to have changed to `Explore AppMaps`, which will cause this to fail. This is referenced in at least a couple of different areas.

2022-07-21 13:01 UTC, dustinbyrne commented
The build is passing but there are four tests failing, presumably due to a rebase? There's an `|| true` in `.travis.yml` allowing the build to pass regardless of the test results. We can probably remove that now.

2022-07-21 13:13 UTC, ahtrotta commented on test/system/tests/instructions.test.ts
>      await driver.instructionsWebview.clickButton('View problems');
This button has changed and the label is now `'Open the PROBLEMS tab'`.

2022-07-21 13:24 UTC, ahtrotta commented on test/system/tests/instructions.test.ts
>      await driver.instructionsWebview.clickButton('View problems');
This button has changed and the label is now 'Open the PROBLEMS tab'.

2022-07-22 14:18 UTC, apotterri commented on test/system/tests/instructions.test.ts
>      await driver.instructionsWebview.getPageByTitle('Open AppMaps').waitFor();
Fixed.

2022-07-22 14:18 UTC, apotterri commented on test/system/tests/instructions.test.ts
>      await driver.instructionsWebview.clickButton('View problems');
Fixed.

2022-07-22 14:18 UTC, apotterri commented on test/system/tests/instructions.test.ts
>      await driver.instructionsWebview.clickButton('View problems');
Fixed.

2022-07-22 14:20 UTC, apotterri commented
> The build is passing but there are four tests failing, presumably due to a rebase? There's an `|| true` in `.travis.yml` allowing the build to pass regardless of the test results. We can probably remove that now.

I've rearranged this a bit, so we're only using `|| true` for `test:extension`. These tests still fail intermittently.

2022-07-22 18:33 UTC, ahtrotta approved these changes

2022-07-22 19:52 UTC, merged

2022-07-22 23:13 UTC, appland-release commented
:tada: This PR is included in version 0.39.0 :tada:

The release is available on:
- `v0.39.0`
- [GitHub release](https://github.com/applandinc/vscode-appland/releases/tag/v0.39.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: