Re-adding doc updates to a new branch
applandinc/vscode-appland pull request #82
Opened 2021-01-11 17:41 UTC by ptrdvrk

Updated documentation:
* README.md, doc/README-JAVA.md & doc/README-RUBY.md language-specific setup instructions
* Doc images (.png and .gif) in doc/media/

2021-01-11 19:06 UTC, kgilpin commented on README.md
> +![AppLand diagrams](./doc/media/002.gif "AppLand diagrams")
I think it's important that we show opening the Source code in this clip, it doesn't appear to do so.

2021-01-11 19:06 UTC, kgilpin commented on README.md
> +- Component diagrams akin to UML class diagrams
Actually the Component diagram is not very similar to a UML class diagram. It's akin to a C4 Component diagram. I don't know if there is a similar diagram in UML. 

Class diagrams show class inheritance. We don't do that at all.

https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-class-diagram/

2021-01-11 19:06 UTC, kgilpin commented on README.md
> +![Component diagram](./doc/media/001.gif "Component diagram")
This video should also open the source code.

2021-01-11 19:06 UTC, kgilpin commented on README.md
> +- Use the built-in [screencast mode](https://dzhavat.github.io/2019/09/18/screencast-mode-in-vs-code.html) that will help your audience better follow your mouse and keyboard actions
I don't think this is built-in? It looks like it's another extension.

2021-01-11 19:06 UTC, kgilpin commented on README.md
> +1. [Sign-up](https://app.land) to app.land , create an account for your organization and invite others to join
Use "sign up for" or "sign in to". Fix comma after app.land.

2021-01-11 21:12 UTC, ptrdvrk commented on README.md
> +- [for Ruby](./doc/README-RUBY.md)
Similar links work in other extensions, i.e. eslint:
* `[change log](./CHANGELOG.md)`
* `![ESLint Dialog](images/2_1_10/eslint-dialog.png)`

2021-01-11 21:14 UTC, ptrdvrk commented on README.md
> +![AppLand diagrams](./doc/media/002.gif "AppLand diagrams")
Yes, we'll need updated animations before the launch.

2021-01-11 21:14 UTC, ptrdvrk commented on README.md
> +![Component diagram](./doc/media/001.gif "Component diagram")
Ditto.

2021-01-11 21:15 UTC, ptrdvrk commented on README.md
> +- Component diagrams akin to UML class diagrams
Please suggest an alternative text. Elizabeth asked to remove C4 reference here.

2021-01-11 21:22 UTC, ptrdvrk commented on README.md
> +- Use the built-in [screencast mode](https://dzhavat.github.io/2019/09/18/screencast-mode-in-vs-code.html) that will help your audience better follow your mouse and keyboard actions
It is built-in functionality, not an extension. The linked article explains nicely how the user used the mode to showcase his own extension. You can try it yourself: ctrl+shift+P, Toggle Screencast Mode.

2021-01-11 21:26 UTC, ptrdvrk commented on README.md
> +1. [Sign-up](https://app.land) to app.land , create an account for your organization and invite others to join
Done, thank you.

2021-01-11 21:41 UTC, ptrdvrk commented on README.md
> +- Component diagrams akin to UML class diagrams
I've updated the text to similar one we use in Pendo guides: https://github.com/applandinc/vscode-appland/pull/82/commits/8faea30d342e28c6a026e2770e7273d6a9b457f3

2021-01-12 18:30 UTC, dustinbyrne requested changes

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +- Onboard to code architecture, with no extra work for the team
It may just be me, but this bullet point reads a bit strangely.

> Get up to speed on existing code architecture
> Get up to speed on existing code architecture without depending on teammates

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +AppLand is a self-contained Visual Code extension that automatically records and diagrams software behavior by executing test cases.  Now you can walk through automatically generated white-board styl
> [...] records and diagrams software behavior by executing test cases

What about manual recordings?

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +- Code linkage of the diagram to the source code it relates to
Can this merge with the previous section or be left out?

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +AppLand records behavior of running code as [AppMaps](https://github.com/applandinc/appmap) during test execution and visualizes them in interactive diagrams.
This is almost identical to the first line in this README. Is this intentional?

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +AppLand is a self-contained Visual Code extension that automatically records and diagrams software behavior by executing test cases.  Now you can walk through automatically generated white-board styl
> AppLand is a self-contained Visual Code extension

We're more than just a VS Code extension. `Visual Code` should also be `Visual Studio Code`.

Maybe something like:
> The AppLand extension for Visual Studio Code [...]

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +    - [AppMap client for Java](https://github.com/applandinc/appmap-java)
We have two links a few lines above:
> - for Ruby
> - for Java

This looks duplicative, but the links go to different places. As I've mentioned before, I'd really prefer to keep client documentation separate from the extension documentation, as none of the extension behavior varies across language.

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +    - `AppLand: Open most recently modified AppMap file`
This bullet point doesn't feel like it belongs in `Quickstart`. It's also described immediately after in a different section, so consider dropping it.

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +Then re-run the tests to record new AppMap files with the updated configuration.
Isn't this documented elsewhere?

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +Simply share your `appmap.yml` configuration file with others. Use of a git repository is recommended for tracking and sharing updates among members of your team.
Isn't this documented elsewhere?

The recommendation would be to store it in source control.

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +AppLand has other solutions which help you profile and automatically diagram software through dynamic analysis, without relying on test cases.  We have also hosted analytics solutions to analyze code
Why are we evading the question here?

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> +Let us know by joining the discussion on [Discord](https://discord.com/invite/N9VUap6) or submit your issue on [GitHub](https://github.com/applandinc/vscode-appland).
Can we move these links back to the top?

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> + - Requires VS Code 1.50 and newer
Drop this section

2021-01-12 18:30 UTC, dustinbyrne commented on README.md
> + - Java: JUnit framework
This should live close to where we link to our Java and Ruby clients.

2021-01-12 18:30 UTC, dustinbyrne commented on doc/README-JAVA.md
> +![Java Test Explorer](./media/006.png "Java Test Explorer")
Installing additional extensions isn't required and only stands to complicate the process. Can we drop this?

2021-01-12 18:30 UTC, dustinbyrne commented on doc/README-JAVA.md
> +The `appmap-java` project on GitHub has [instructions for running the `appmap.jar` Java agent within the Maven, Surefire, or Gradle](https://github.com/applandinc/appmap-java/blob/master/README.md#ot
This is all documented elsewhere. Why don't we link to it instead?

2021-01-12 18:30 UTC, dustinbyrne commented on doc/README-RUBY.md
> +Alternatively, you can generate AppMaps from tests manually from the command line. See instructions in [https://github.com/applandinc/appmap-ruby](https://github.com/applandinc/appmap-ruby#rspec)
Installing additional extensions isn't required and only stands to complicate the process. Can we drop this?

2021-01-12 18:30 UTC, dustinbyrne commented on doc/README-RUBY.md
> +The following sections provide detailed instructions for recording AppMaps from RSpec, Minitest, and Cucumber test cases.
This is all documented elsewhere. Why don't we link to it instead?

2021-01-12 19:02 UTC, Daniel-Warner-X commented on README.md
> +- Code linkage of the diagram to the source code it relates to
This is a clear and concise summary. Much easier to read than the paragraphs of text. In my opinion, we should leave it in.

2021-01-12 19:12 UTC, dustinbyrne commented on README.md
> +- Code linkage of the diagram to the source code it relates to
Thanks for the feedback. I'm okay with keeping it 👍

2021-01-12 19:24 UTC, ptrdvrk commented on README.md
> +AppLand is a self-contained Visual Code extension that automatically records and diagrams software behavior by executing test cases.  Now you can walk through automatically generated white-board styl
Fair point, updating.

2021-01-12 19:31 UTC, ptrdvrk commented on README.md
> +AppLand is a self-contained Visual Code extension that automatically records and diagrams software behavior by executing test cases.  Now you can walk through automatically generated white-board styl
We don't want to reference the browser extension. What other manual recording docs can we point the users to?

2021-01-12 19:32 UTC, ptrdvrk commented on README.md
> +AppLand records behavior of running code as [AppMaps](https://github.com/applandinc/appmap) during test execution and visualizes them in interactive diagrams.
Yes, it is a short recap of what follows in this chapter.

2021-01-12 19:36 UTC, ptrdvrk commented on README.md
> +    - [AppMap client for Java](https://github.com/applandinc/appmap-java)
Fair point about the links looking duplicative, I am changing the links to the detailed instruction pages. The goal of the detailed pages is not to duplicate content but to provide easy to follow guide even for users who do not have a black belt in Ruby or Java app development in VSCode, yet.

2021-01-12 19:36 UTC, ptrdvrk commented on README.md
> +    - `AppLand: Open most recently modified AppMap file`
OK.

2021-01-12 19:40 UTC, ptrdvrk commented on README.md
> +Depending on the test run and functionality covered, you should see a viewer with a diagram similar to this one:
I asked Kevin about the terminology, he uses viewer (and he also wrote this line).

2021-01-12 19:42 UTC, ptrdvrk commented on README.md
> +Then re-run the tests to record new AppMap files with the updated configuration.
Where? This is just a pointer to other docs with a context.

2021-01-12 20:04 UTC, ptrdvrk commented on README.md
> +Let us know by joining the discussion on [Discord](https://discord.com/invite/N9VUap6) or submit your issue on [GitHub](https://github.com/applandinc/vscode-appland).
OK

2021-01-12 20:04 UTC, ptrdvrk commented on README.md
> + - Requires VS Code 1.50 and newer
Done.

2021-01-12 20:34 UTC, ptrdvrk commented on README.md
> +AppLand has other solutions which help you profile and automatically diagram software through dynamic analysis, without relying on test cases.  We have also hosted analytics solutions to analyze code
What is the answer we are evading? The decision was not to bring the browser extension to V0.

2021-01-13 23:40 UTC, ptrdvrk commented on README.md
> + - Java: JUnit framework
Done

2021-01-14 18:35 UTC, ptrdvrk commented on doc/README-RUBY.md
> +Alternatively, you can generate AppMaps from tests manually from the command line. See instructions in [https://github.com/applandinc/appmap-ruby](https://github.com/applandinc/appmap-ruby#rspec)
Removed from README.md.

2021-01-14 18:36 UTC, ptrdvrk commented on doc/README-RUBY.md
> +The following sections provide detailed instructions for recording AppMaps from RSpec, Minitest, and Cucumber test cases.
Removed from README.md

2021-01-14 21:02 UTC, Daniel-Warner-X approved these changes

2021-01-14 21:02 UTC, merged